name: 🐛 Bug report
description: Create a report to help us improve

body:
- type: dropdown
  attributes:
   label: Sport
   options:
    - Football
    - Basketball
    - Baseball
    - Hockey
  validations:
    required: true

- type: textarea
  attributes:
    label: Summary
    description: Explain the problem briefly below.
  validations:
    required: true

- type: textarea
  attributes:
    label: Logs/Data
    description: >-
      If you have any logs or data when the bug occurred, please provide it here.
