name:  ✨ Feature request
description: Suggest an idea for this project

body:
- type: dropdown
  attributes:
    label: Sport
    options:
     - All
     - Football
     - Basketball
     - Baseball
     - Hockey
  validations:
    required: true

- type: textarea
  attributes:
    label: Summary
    description: Describe the new feature/improvement briefly below.
  validations:
    required: true
